#!/usr/bin/env node
// Code-derived documentation facts (review R7 7.1).
//
// The README's defaults table used to be typed by hand and drifted from the
// schema (and HANDOFF's copy drifted further: maxTokens 8192 vs 64000, P
// fallback 1 vs 0, "maxWorkers=1" vs auto 4). This script renders it from the
// built config schema and the exported operational limits instead:
//
//   node scripts/doc-facts.mjs --write   rewrite the generated block in README.md
//   node scripts/doc-facts.mjs --check   exit 1 when README.md is stale
//
// Only the "notes" column is prose. Values, ranges and choices come from
// `Config.dict` (schema meta), so they cannot disagree with the code. Test
// counts are deliberately NOT rendered anywhere: CI's spec reporter prints the
// authoritative number on every run. scripts/tests/doc-truth.test.mjs runs
// --check's logic in `npm test`. Requires `lib/` (npm run build:host).
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const lib = (rel) => import(pathToFileURL(path.join(root, 'lib', rel)).href)

export const BEGIN = '<!-- doc-facts:defaults:begin (generated by scripts/doc-facts.mjs; do not edit) -->'
export const END = '<!-- doc-facts:defaults:end -->'

/** One line of meaning per key; everything else in the row is derived.
 *  `{NAME}` placeholders are filled from exported constants (renderDefaults). */
const NOTES = {
  enabled: 'legacy five-lane idle verifier; opt-in since review R7 (each gated idle turn = `routes` calls)',
  autoFeedback: 'send the legacy verdict back to the agent as a follow-up',
  routes: 'legacy lanes per verification',
  scoreThreshold: 'legacy: median score below which feedback is considered',
  disagreementThreshold: 'legacy: lane dispersion above which feedback is considered',
  maxFeedbackPerSession: 'legacy feedback quota per session',
  timeoutMs: 'per legacy lane call',
  maxTokens: 'per legacy lane call (thinking is deducted from it)',
  temperature: 'legacy lane sampling temperature',
  baseURL: 'verifier endpoint for both paths (third-party relay by default; review R1 1.9 owner decision pending)',
  model: 'verifier model for both paths',
  apiKeyEnv: 'environment variable holding the verifier key',
  verifierEffort: 'thinking effort for lane and tournament verifiers (`off` disables thinking)',
  allowLabelFallback: 'accept a score label without logprobs (off: fail instead)',
  divergenceGuard: 'legacy: suppress feedback when the median is high and most lanes found no concrete defect',
  divergenceGuardMedian: 'legacy: median at or above which the divergence guard applies',
  skipStatusContinuation: 'legacy: do not verify status-only continuation turns',
  selectionNotify: 'post a settlement notice for manual selections',
  selectionMode: 'autopilot best-of-N on source turns; opt-in since review R7 (`auto` = heuristic admission, `always` = every safe task)',
  selectionModelStrategy: '`quality-first` puts every candidate on the first live model; `exploration` rotates',
  selectionProvider: 'DSH provider for candidate agents',
  selectionModels: 'quality-ordered, comma-separated; custom IDs are probed directly',
  selectionStandardCandidates: 'N for standard tasks',
  selectionDeepCandidates: 'N for deep tasks',
  selectionEvaluations: 'K (verifier repetitions); deep tasks use at least 2',
  selectionPivots: 'P (pivot iterations, O(N*P) comparisons)',
  selectionCandidateTimeoutMs: 'per candidate rollout',
  selectionSelectTimeoutMs: 'ranking budget (preflight and ranking each get their own deadline)',
  selectionMarginThreshold: 'top-2 margin below which the run abstains; provisional, calibrated for one condition only (review R3 3.1)',
  selectionUncalibratedMarginPolicy: '`flag` marks winners from uncalibrated conditions; `abstain` refuses them',
  selectionProbeEnabled: '1-token liveness probe of candidate models before planning',
  selectionPostAuditTestCommand: 'optional test command for the delivery post-audit (empty: not run)',
  selectionVerifierWorkers: 'tournament concurrency; `0` = auto ({AUTO_VERIFIER_WORKERS})',
  verifierMinIntervalMs: 'token-bucket spacing shared by both verifier paths; `0` = off',
  verifierSmallModel: 'cheaper model for mechanical legacy lanes; empty = off',
}

const cell = (value) => String(value).replace(/\|/g, '\\|')
const code = (value) => '`' + cell(value === '' ? "''" : value) + '`'

function allowed(schema) {
  if (schema.type === 'union') return schema.list.map((item) => code(item.value)).join(' / ')
  if (schema.type === 'boolean') return '`true` / `false`'
  const meta = schema.meta ?? {}
  if (schema.type === 'number' && meta.min !== undefined && meta.max !== undefined) return code(meta.min) + '..' + code(meta.max) + (meta.step && meta.step !== 1 ? ' step ' + meta.step : '')
  if (schema.type === 'string' && meta.max !== undefined) return 'string, at most ' + meta.max + ' chars'
  return schema.type
}

export async function renderDefaults() {
  const { Config } = await lib('config.js')
  const { API_RATE_LIMITS } = await lib('api.js')
  const { SELECTIONS_HISTORY_LIMIT, PREFLIGHT_OK_TTL_MS, AUTO_VERIFIER_WORKERS } = await lib('selection/host.js')
  const constants = { AUTO_VERIFIER_WORKERS }
  const note = (key) => (NOTES[key] ?? '').replace(/\{(\w+)\}/g, (whole, name) => {
    if (!(name in constants)) throw new Error('doc-facts: unknown placeholder ' + whole)
    return String(constants[name])
  })
  const rows = ['| Setting | Default | Allowed | Notes |', '|---|---|---|---|']
  const missing = []
  for (const [key, schema] of Object.entries(Config.dict)) {
    if (!NOTES[key]) missing.push(key)
    rows.push('| `' + key + '` | ' + code(schema.meta?.default) + ' | ' + allowed(schema) + ' | ' + cell(note(key)) + ' |')
  }
  if (missing.length > 0) throw new Error('doc-facts: no note for config key(s) ' + missing.join(', ') + ' (add one to NOTES)')
  const limits = [
    '| Limit | Value |', '|---|---|',
    '| `POST /select` admissions | ' + API_RATE_LIMITS.selectPerHour + ' per hour (sliding window) |',
    '| `POST /eval` / `/probe` / `/verify` | ' + API_RATE_LIMITS.evalPerMinute + ' / ' + API_RATE_LIMITS.probePerMinute + ' / ' + API_RATE_LIMITS.verifyPerMinute + ' per minute |',
    '| selection ledger window | ' + SELECTIONS_HISTORY_LIMIT + ' records (audit packs outside it are collected) |',
    '| verifier preflight success cache | ' + PREFLIGHT_OK_TTL_MS / 60_000 + ' minutes |',
  ]
  return [BEGIN, '', rows.join('\n'), '', limits.join('\n'), '', END].join('\n')
}

/** Documents that state current behavior (README's Documentation Map).
 *  Journals and dated records (HANDOFF.md, docs/*HISTORY*, reviews,
 *  preregistrations) are records of their dates and are not linted. */
export const AUTHORITATIVE_DOCS = [
  'README.md',
  'docs/ARCHITECTURE.md',
  'API-BOUNDARY-DECISIONS.md',
  'bridge/PROTOCOL.md',
  'docs/VERIFIER-SCHEDULER.md',
  'eval/calibration/README.md',
]

/** Drift findings for one authoritative document (review R7 7.1):
 *  hand-written test counts (CI prints the real one), author-machine paths,
 *  "`key` ... default X" prose that disagrees with the schema, and margin-gate
 *  values other than the shipped threshold. */
export function lintDoc(text, defaults) {
  const findings = []
  const escape = (value) => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  text.split('\n').forEach((line, index) => {
    const at = 'line ' + (index + 1)
    if (/\b(\d{3})\s*\/\s*\1\b|\b\d{3} (?:regressions|tests)\b/.test(line)) findings.push(at + ': hand-written test count')
    if (/\b[CD]:[\\/]/.test(line)) findings.push(at + ': author-machine path')
    for (const [key, value] of Object.entries(defaults)) {
      const claim = new RegExp('`?\\b' + escape(key) + '\\b`?[^|\\n]{0,40}?\\bdefaults?\\b(?: is| to|:|=)?\\s*`?([\\w./:-]+)').exec(line)
      const written = claim?.[1]
      if (written && written !== String(value) && !(value === '' && (written === 'empty' || written === "''"))) findings.push(at + ': ' + key + ' default written as ' + written + ', schema says ' + JSON.stringify(value))
    }
    if (/margin gate|selectionMarginThreshold/.test(line)) {
      for (const decimal of line.match(/\b0\.0\d+\b/g) ?? []) {
        if (Number(decimal) !== defaults.selectionMarginThreshold) findings.push(at + ': margin value ' + decimal + ', shipped threshold is ' + defaults.selectionMarginThreshold)
      }
    }
  })
  return findings
}

export function replaceBlock(text, block) {
  const start = text.indexOf(BEGIN)
  const end = text.indexOf(END)
  if (start < 0 || end < start) throw new Error('doc-facts: README.md has no generated defaults block')
  return text.slice(0, start) + block + text.slice(end + END.length)
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const readme = path.join(root, 'README.md')
  const current = readFileSync(readme, 'utf8')
  const next = replaceBlock(current, await renderDefaults())
  if (process.argv.includes('--write')) {
    if (next !== current) writeFileSync(readme, next)
    console.log(next === current ? 'doc-facts: README.md already current' : 'doc-facts: README.md updated')
  } else if (next !== current) {
    console.error('doc-facts: README.md defaults block is stale; run node scripts/doc-facts.mjs --write')
    process.exit(1)
  } else {
    console.log('doc-facts: README.md current')
  }
}
